<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TieredPGO>true</TieredPGO>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="acryptohashnet" />
		<PackageReference Include="BenchmarkDotNet" />
		<PackageReference Include="Blake3" />
		<PackageReference Include="BouncyCastle.Cryptography" />
		<PackageReference Include="HashDepot" />
		<PackageReference Include="nebulae.dotSHA3" />
		<PackageReference Include="SauceControl.Blake2Fast" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\StreamHash.Core\StreamHash.Core.csproj" />
	</ItemGroup>

</Project>
