using StreamHash.Core.Testing;
using Xunit;

namespace StreamHash.Core.Tests.ReferenceData;

/// <summary>
/// Tests that verify StreamHash native implementations against reference hash values.
/// </summary>
/// <remarks>
/// These tests verify that Groestl and JH implementations produce correct output
/// by comparing against values generated by BouncyCastle and other reference implementations.
/// </remarks>
public class ReferenceHashVerificationTests {
	private static string ToHex(byte[] bytes) => Convert.ToHexStringLower(bytes);

	// ============================================================================
	// Groestl-256 Tests
	// ============================================================================

	[Fact]
	public void Groestl256_64KB_MatchesReference() {
		using var hasher = new Groestl256();
		hasher.Update(TestDataGenerator.File64KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB64.Groestl256, result);
	}

	[Fact]
	public void Groestl256_69KB_MatchesReference() {
		using var hasher = new Groestl256();
		hasher.Update(TestDataGenerator.File69KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB69.Groestl256, result);
	}

	[Fact]
	public void Groestl256_767KB_MatchesReference() {
		using var hasher = new Groestl256();
		hasher.Update(TestDataGenerator.File767KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB767.Groestl256, result);
	}

	[Fact]
	public void Groestl256_3MB_MatchesReference() {
		using var hasher = new Groestl256();
		hasher.Update(TestDataGenerator.File3MB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.MB3.Groestl256, result);
	}

	[Fact]
	public void Groestl256_38MB_MatchesReference() {
		using var hasher = new Groestl256();
		hasher.Update(TestDataGenerator.File38MB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.MB38.Groestl256, result);
	}

	// ============================================================================
	// Groestl-512 Tests
	// ============================================================================

	[Fact]
	public void Groestl512_64KB_MatchesReference() {
		using var hasher = new Groestl512();
		hasher.Update(TestDataGenerator.File64KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB64.Groestl512, result);
	}

	[Fact]
	public void Groestl512_69KB_MatchesReference() {
		using var hasher = new Groestl512();
		hasher.Update(TestDataGenerator.File69KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB69.Groestl512, result);
	}

	[Fact]
	public void Groestl512_767KB_MatchesReference() {
		using var hasher = new Groestl512();
		hasher.Update(TestDataGenerator.File767KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB767.Groestl512, result);
	}

	[Fact]
	public void Groestl512_3MB_MatchesReference() {
		using var hasher = new Groestl512();
		hasher.Update(TestDataGenerator.File3MB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.MB3.Groestl512, result);
	}

	[Fact]
	public void Groestl512_38MB_MatchesReference() {
		using var hasher = new Groestl512();
		hasher.Update(TestDataGenerator.File38MB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.MB38.Groestl512, result);
	}

	// ============================================================================
	// JH-256 Tests
	// ============================================================================

	[Fact]
	public void JH256_64KB_MatchesReference() {
		using var hasher = new JH256();
		hasher.Update(TestDataGenerator.File64KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB64.JH256, result);
	}

	[Fact]
	public void JH256_69KB_MatchesReference() {
		using var hasher = new JH256();
		hasher.Update(TestDataGenerator.File69KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB69.JH256, result);
	}

	[Fact]
	public void JH256_767KB_MatchesReference() {
		using var hasher = new JH256();
		hasher.Update(TestDataGenerator.File767KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB767.JH256, result);
	}

	[Fact]
	public void JH256_3MB_MatchesReference() {
		using var hasher = new JH256();
		hasher.Update(TestDataGenerator.File3MB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.MB3.JH256, result);
	}

	[Fact]
	public void JH256_38MB_MatchesReference() {
		using var hasher = new JH256();
		hasher.Update(TestDataGenerator.File38MB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.MB38.JH256, result);
	}

	// ============================================================================
	// JH-512 Tests
	// ============================================================================

	[Fact]
	public void JH512_64KB_MatchesReference() {
		using var hasher = new JH512();
		hasher.Update(TestDataGenerator.File64KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB64.JH512, result);
	}

	[Fact]
	public void JH512_69KB_MatchesReference() {
		using var hasher = new JH512();
		hasher.Update(TestDataGenerator.File69KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB69.JH512, result);
	}

	[Fact]
	public void JH512_767KB_MatchesReference() {
		using var hasher = new JH512();
		hasher.Update(TestDataGenerator.File767KB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB767.JH512, result);
	}

	[Fact]
	public void JH512_3MB_MatchesReference() {
		using var hasher = new JH512();
		hasher.Update(TestDataGenerator.File3MB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.MB3.JH512, result);
	}

	[Fact]
	public void JH512_38MB_MatchesReference() {
		using var hasher = new JH512();
		hasher.Update(TestDataGenerator.File38MB);
		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.MB38.JH512, result);
	}

	// ============================================================================
	// Streaming Verification Tests (multiple Update calls)
	// ============================================================================

	[Fact]
	public void Groestl256_StreamingUpdate_MatchesReference() {
		var data = TestDataGenerator.File64KB;
		using var hasher = new Groestl256();

		// Feed data in chunks of varying sizes
		int offset = 0;
		int[] chunkSizes = [1, 7, 64, 128, 1000, 63, 127, 1];
		int chunkIndex = 0;

		while (offset < data.Length) {
			int chunkSize = Math.Min(chunkSizes[chunkIndex % chunkSizes.Length], data.Length - offset);
			hasher.Update(data.AsSpan(offset, chunkSize));
			offset += chunkSize;
			chunkIndex++;
		}

		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB64.Groestl256, result);
	}

	[Fact]
	public void JH256_StreamingUpdate_MatchesReference() {
		var data = TestDataGenerator.File64KB;
		using var hasher = new JH256();

		// Feed data in chunks of varying sizes
		int offset = 0;
		int[] chunkSizes = [1, 7, 64, 128, 1000, 63, 127, 1];
		int chunkIndex = 0;

		while (offset < data.Length) {
			int chunkSize = Math.Min(chunkSizes[chunkIndex % chunkSizes.Length], data.Length - offset);
			hasher.Update(data.AsSpan(offset, chunkSize));
			offset += chunkSize;
			chunkIndex++;
		}

		var result = ToHex(hasher.FinalizeBytes());
		Assert.Equal(ReferenceHashValues.KB64.JH256, result);
	}

	// ============================================================================
	// Reset Tests
	// ============================================================================

	[Fact]
	public void Groestl256_Reset_ProducesSameResult() {
		using var hasher = new Groestl256();

		// First hash
		hasher.Update(TestDataGenerator.File64KB);
		var result1 = ToHex(hasher.FinalizeBytes());

		// Reset and hash again
		hasher.Reset();
		hasher.Update(TestDataGenerator.File64KB);
		var result2 = ToHex(hasher.FinalizeBytes());

		Assert.Equal(result1, result2);
		Assert.Equal(ReferenceHashValues.KB64.Groestl256, result1);
	}

	[Fact]
	public void JH256_Reset_ProducesSameResult() {
		using var hasher = new JH256();

		// First hash
		hasher.Update(TestDataGenerator.File64KB);
		var result1 = ToHex(hasher.FinalizeBytes());

		// Reset and hash again
		hasher.Reset();
		hasher.Update(TestDataGenerator.File64KB);
		var result2 = ToHex(hasher.FinalizeBytes());

		Assert.Equal(result1, result2);
		Assert.Equal(ReferenceHashValues.KB64.JH256, result1);
	}
}
