namespace StreamHash.Core.Testing;

/// <summary>
/// Generates deterministic test data files using a canonical random seed.
/// </summary>
/// <remarks>
/// <para>
/// This class provides lazily-generated test files of various sizes for benchmarking
/// and testing hash algorithms. All files use the same canonical seed (0x5472_6565_4861_7368 = "TreeHash")
/// ensuring reproducible results across test runs.
/// </para>
/// <para>
/// <b>Available Test Files:</b>
/// <list type="bullet">
/// <item><b>64 KB</b> - Small file for quick benchmarks</item>
/// <item><b>69 KB</b> - Odd size to test non-aligned boundaries</item>
/// <item><b>767 KB</b> - Medium file approaching 1MB</item>
/// <item><b>3 MB</b> - Standard medium-large file</item>
/// <item><b>38.3 MB</b> - Large file for streaming performance tests</item>
/// </list>
/// </para>
/// <para>
/// <b>Future Large Files (not generated by default):</b>
/// <list type="bullet">
/// <item><b>100 MB</b> - Large streaming test</item>
/// <item><b>212 MB</b> - Very large file</item>
/// <item><b>765 MB</b> - Near-gigabyte test</item>
/// <item><b>1.37 GB</b> - Gigabyte-scale test</item>
/// </list>
/// </para>
/// </remarks>
public static class TestDataGenerator {
	// ========== Canonical Seed ==========

	/// <summary>
	/// Canonical random seed for all test data generation.
	/// Value: 0x5472_6565_4861_7368 = "TreeHash" in ASCII (sort of).
	/// This ensures all test files are identical across runs.
	/// </summary>
	public const long CanonicalSeed = 0x5472_6565_4861_7368;

	/// <summary>
	/// The seed as an integer for Random constructor.
	/// Uses lower 32 bits XORed with upper 32 bits for better distribution.
	/// </summary>
	public static int SeedAsInt => unchecked((int)(CanonicalSeed ^ (CanonicalSeed >> 32)));

	// ========== File Size Constants ==========

	/// <summary>64 KB = 65,536 bytes</summary>
	public const int Size64KB = 64 * 1024;

	/// <summary>69 KB = 70,656 bytes (odd size for boundary testing)</summary>
	public const int Size69KB = 69 * 1024;

	/// <summary>767 KB = 785,408 bytes</summary>
	public const int Size767KB = 767 * 1024;

	/// <summary>3 MB = 3,145,728 bytes</summary>
	public const int Size3MB = 3 * 1024 * 1024;

	/// <summary>38.3 MB = 40,160,051 bytes (prime-ish number)</summary>
	public const int Size38MB = 40_160_051;

	/// <summary>100 MB = 104,857,600 bytes (future use)</summary>
	public const int Size100MB = 100 * 1024 * 1024;

	/// <summary>212 MB = 222,298,112 bytes (future use)</summary>
	public const int Size212MB = 212 * 1024 * 1024;

	/// <summary>765 MB = 802,160,640 bytes (future use)</summary>
	public const int Size765MB = 765 * 1024 * 1024;

	/// <summary>1.37 GB = 1,471,026,380 bytes (future use)</summary>
	public const int Size1_37GB = 1_471_026_380;

	// ========== Lazy File Generation ==========

	private static readonly Lazy<byte[]> _file64KB = new(() => GenerateData(Size64KB));
	private static readonly Lazy<byte[]> _file69KB = new(() => GenerateData(Size69KB));
	private static readonly Lazy<byte[]> _file767KB = new(() => GenerateData(Size767KB));
	private static readonly Lazy<byte[]> _file3MB = new(() => GenerateData(Size3MB));
	private static readonly Lazy<byte[]> _file38MB = new(() => GenerateData(Size38MB));

	// Future large files - not generated by default to save memory
	private static byte[]? _file100MB;
	private static byte[]? _file212MB;
	private static byte[]? _file765MB;
	private static byte[]? _file1_37GB;

	// ========== Static Getters ==========

	/// <summary>Gets the 64 KB test file (lazily generated).</summary>
	public static byte[] File64KB => _file64KB.Value;

	/// <summary>Gets the 69 KB test file (lazily generated).</summary>
	public static byte[] File69KB => _file69KB.Value;

	/// <summary>Gets the 767 KB test file (lazily generated).</summary>
	public static byte[] File767KB => _file767KB.Value;

	/// <summary>Gets the 3 MB test file (lazily generated).</summary>
	public static byte[] File3MB => _file3MB.Value;

	/// <summary>Gets the 38.3 MB test file (lazily generated).</summary>
	public static byte[] File38MB => _file38MB.Value;

	/// <summary>
	/// Gets the 100 MB test file (generated on first access, not cached by default).
	/// Call <see cref="PreloadLargeFiles"/> to cache.
	/// </summary>
	public static byte[] File100MB => _file100MB ??= GenerateData(Size100MB);

	/// <summary>
	/// Gets the 212 MB test file (generated on first access, not cached by default).
	/// Call <see cref="PreloadLargeFiles"/> to cache.
	/// </summary>
	public static byte[] File212MB => _file212MB ??= GenerateData(Size212MB);

	/// <summary>
	/// Gets the 765 MB test file (generated on first access, not cached by default).
	/// Call <see cref="PreloadLargeFiles"/> to cache.
	/// </summary>
	public static byte[] File765MB => _file765MB ??= GenerateData(Size765MB);

	/// <summary>
	/// Gets the 1.37 GB test file (generated on first access, not cached by default).
	/// Call <see cref="PreloadLargeFiles"/> to cache.
	/// </summary>
	public static byte[] File1_37GB => _file1_37GB ??= GenerateData(Size1_37GB);

	// ========== Generation Methods ==========

	/// <summary>
	/// Generates deterministic random data of the specified size using the canonical seed.
	/// </summary>
	/// <param name="size">The number of bytes to generate.</param>
	/// <returns>A byte array filled with deterministic random data.</returns>
	public static byte[] GenerateData(int size) {
		var data = new byte[size];
		var random = new Random(SeedAsInt);
		random.NextBytes(data);
		return data;
	}

	/// <summary>
	/// Gets a test file by size category.
	/// </summary>
	/// <param name="category">The size category.</param>
	/// <returns>The test file data.</returns>
	public static byte[] GetFile(TestFileSize category) => category switch {
		TestFileSize.KB64 => File64KB,
		TestFileSize.KB69 => File69KB,
		TestFileSize.KB767 => File767KB,
		TestFileSize.MB3 => File3MB,
		TestFileSize.MB38 => File38MB,
		TestFileSize.MB100 => File100MB,
		TestFileSize.MB212 => File212MB,
		TestFileSize.MB765 => File765MB,
		TestFileSize.GB1_37 => File1_37GB,
		_ => throw new ArgumentOutOfRangeException(nameof(category))
	};

	/// <summary>
	/// Gets the size in bytes for a test file category.
	/// </summary>
	public static int GetSize(TestFileSize category) => category switch {
		TestFileSize.KB64 => Size64KB,
		TestFileSize.KB69 => Size69KB,
		TestFileSize.KB767 => Size767KB,
		TestFileSize.MB3 => Size3MB,
		TestFileSize.MB38 => Size38MB,
		TestFileSize.MB100 => Size100MB,
		TestFileSize.MB212 => Size212MB,
		TestFileSize.MB765 => Size765MB,
		TestFileSize.GB1_37 => Size1_37GB,
		_ => throw new ArgumentOutOfRangeException(nameof(category))
	};

	/// <summary>
	/// Pre-generates and caches all standard test files (64KB through 38MB).
	/// Call this at the start of a test run to ensure consistent timing.
	/// </summary>
	public static void PreloadStandardFiles() {
		_ = File64KB;
		_ = File69KB;
		_ = File767KB;
		_ = File3MB;
		_ = File38MB;
	}

	/// <summary>
	/// Pre-generates and caches all large test files (100MB through 1.37GB).
	/// WARNING: This will allocate ~2.4 GB of memory!
	/// </summary>
	public static void PreloadLargeFiles() {
		_file100MB = GenerateData(Size100MB);
		_file212MB = GenerateData(Size212MB);
		_file765MB = GenerateData(Size765MB);
		_file1_37GB = GenerateData(Size1_37GB);
	}

	/// <summary>
	/// Clears cached large files to free memory.
	/// </summary>
	public static void ClearLargeFileCache() {
		_file100MB = null;
		_file212MB = null;
		_file765MB = null;
		_file1_37GB = null;
	}

	/// <summary>
	/// Gets all standard test file sizes (64KB through 38MB).
	/// </summary>
	public static IEnumerable<TestFileSize> StandardSizes => [
		TestFileSize.KB64,
		TestFileSize.KB69,
		TestFileSize.KB767,
		TestFileSize.MB3,
		TestFileSize.MB38
	];

	/// <summary>
	/// Gets all large test file sizes (100MB through 1.37GB).
	/// </summary>
	public static IEnumerable<TestFileSize> LargeSizes => [
		TestFileSize.MB100,
		TestFileSize.MB212,
		TestFileSize.MB765,
		TestFileSize.GB1_37
	];

	/// <summary>
	/// Gets all test file sizes.
	/// </summary>
	public static IEnumerable<TestFileSize> AllSizes =>
		StandardSizes.Concat(LargeSizes);
}

/// <summary>
/// Test file size categories.
/// </summary>
public enum TestFileSize {
	/// <summary>64 KB test file</summary>
	KB64,
	/// <summary>69 KB test file (odd size)</summary>
	KB69,
	/// <summary>767 KB test file</summary>
	KB767,
	/// <summary>3 MB test file</summary>
	MB3,
	/// <summary>38.3 MB test file</summary>
	MB38,
	/// <summary>100 MB test file (future)</summary>
	MB100,
	/// <summary>212 MB test file (future)</summary>
	MB212,
	/// <summary>765 MB test file (future)</summary>
	MB765,
	/// <summary>1.37 GB test file (future)</summary>
	GB1_37
}
