global using System;
global using System.Buffers;
global using System.Buffers.Binary;
global using System.Numerics;
global using System.Runtime.CompilerServices;
global using System.Runtime.InteropServices;
global using System.Runtime.Intrinsics;
global using System.Runtime.Intrinsics.X86;
global using System.Runtime.Intrinsics.Arm;
